index:
  path: /
  controller: App\Controller\HomeController::index
blog_post:
  path: /blog/{username}/{slug}
  controller: App\Controller\BlogController::detail
  requirements:
    username: '\w+'
    slug: '\w+'
blog_list:
  path: /blog/{page}
  controller: App\Controller\BlogController::index
  defaults:
    page: 1
  requirements:
    page: '\d+'
contact:
  path: contact-us
  controller: App\Controller\ContactController::index
