index:
  path: /
  controller: App\Controller\HomeController::index
blog_post:
  path: /blog/{username}/{slug}
  controller: App\Controller\BlogController::detail
  requirements:
    username: '\w+'
    slug: '\w+'
blog_list:
  path: /blog/{page}
  controller: App\Controller\BlogController::index
  defaults:
    page: 1
  requirements:
    page: '\d+'
blog_edit:
  path: /edit/{post_id}
  controller: App\Controller\BlogController::index
  requirements:
    post_id: '\d+'
contact:
  path: contact-us
  controller: App\Controller\ContactController::index
save_contact:
  path: contact-us/save
  controller: App\Controller\ContactController::save
register:
  path: register
  controller: App\Controller\UserController::register
new_post:
  path: new
  controller: App\Controller\BlogController::newPost
